Add inset option
sindresorhus/capture-website pull request #62
Opened 2020-11-05 20:41 UTC by krnik

Adds `inset` option as defined in https://github.com/sindresorhus/capture-website/issues/8

Summary: `inset` option changes the size of the screenshot by using [`clip`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagescreenshotoptions) option from puppeteer API.
If the `element` option is also provided, then the `element` will become the "center of attention" instead of the viewbox (window).
If the `fullPage` option is provided with value `true`, then the `inset` option is ignored ([source](https://github.com/puppeteer/puppeteer/blob/e45acce928429d0d1572e16943307a73ebd38d8a/src/common/Page.ts#L1620)).

It will also throw an Error when the resulting `width` or `height` of the screenshot (`clip` option) is equal to `0`. [source](https://github.com/puppeteer/puppeteer/blob/e45acce928429d0d1572e16943307a73ebd38d8a/src/common/Page.ts#L1645).

Closes https://github.com/sindresorhus/capture-website/issues/8

2020-11-05 20:41 UTC, krnik commented on index.js
> +		}
https://github.com/puppeteer/puppeteer/blob/e45acce928429d0d1572e16943307a73ebd38d8a/src/common/Page.ts#L1645

2020-11-05 20:42 UTC, krnik commented on index.js
> +	if (options.inset && !screenshotOptions.fullPage) {
https://github.com/puppeteer/puppeteer/blob/e45acce928429d0d1572e16943307a73ebd38d8a/src/common/Page.ts#L1620

2020-11-21 19:11 UTC, sindresorhus commented
Why did you close? I'm getting to this. I've just been very busy.

2020-11-21 20:56 UTC, krnik commented
Oh, I edited the decription - basically I can't say when I will be able to add the `capture-website-cli` equivalent of this option.

If it's fine to merge this PR and then add this option to the `cli` then I'll repoen it. I'll try to find someone to finish it if time is the essence.

2020-12-01 09:07 UTC, sindresorhus commented
There's no rush. I have a lot of PRs to review, so I won't get to this for at least a week or two anyway.

2020-12-01 09:12 UTC, sindresorhus requested changes

2020-12-01 09:12 UTC, sindresorhus commented on index.js
> +			throw new Error('When using "clip" option the width or height of the screenshot cannot be equal to 0');
```suggestion
			throw new Error('When using the `clip` option, the width or height of the screenshot cannot be equal to 0.');
```

2020-12-01 09:12 UTC, sindresorhus commented on readme.md
> +
The readme and index.d.ts should be fully in sync.

2020-12-01 09:12 UTC, sindresorhus commented on readme.md
> +Type: `object | number`
```suggestion
Type: `object | number`\
```

2021-02-07 12:54 UTC, merged

2021-02-07 12:54 UTC, sindresorhus commented
Thanks :)

Would you able to add this to https://github.com/sindresorhus/capture-website-cli too?

2021-02-15 18:03 UTC, krnik commented
Sure, adding this option as a number is simple (the same value for each side). 

Should I also enable this option so that user can specify top, right, left, bottom values as either an array of options `--inset 10 --inset 15 --inset 10 --inset 15` or simply as a string option `--inset '10,15,10,15'`?
I was thinking about it and I'm not sure what would be the best option here.

2021-02-15 18:15 UTC, sindresorhus commented
Yeah, either a number or `--inset '10,15,10,15'`.