Add `preload` option
sindresorhus/capture-website pull request #66
Opened 2020-11-26 07:17 UTC by brandon93s

#48

2020-11-28 05:58 UTC, sindresorhus requested changes

2020-11-28 05:58 UTC, sindresorhus commented on index.js
> +		preload: undefined,
This is moot.

2020-11-28 05:58 UTC, sindresorhus commented on readme.md
> +##### preload
`preload` sounds like it could be a boolean that sets whether to preload it.

2020-11-28 05:58 UTC, sindresorhus commented on readme.md
> +Inject a function to be executed prior to navigation; useful for [altering the JavaScript environment](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefuncti
Can you mention a few common use-cases? Just for lazy people.

2021-01-08 17:12 UTC, sindresorhus commented
Bump :)

2021-01-08 17:13 UTC, sindresorhus commented
Would you be willing to add this to the CLI version too?

2021-02-07 16:41 UTC, closed without merging

2021-02-07 16:58 UTC, brandon93s commented
Moved to https://github.com/sindresorhus/capture-website/pull/76.