workaround fullPage clipping bug by using clip
sindresorhus/capture-website pull request #95
Opened 2021-12-25 13:00 UTC by shemgp

Fixes: #1 

Actually, puppeteer, when using `fullPage: true` does get the whole screen, so no need to scroll around when capturing FIXED items. (So the issueHunt bounty might have to go to someone since it's already fixed.)

However, puppeteer does clip the body's margin-right: ![clipped](https://user-images.githubusercontent.com/1734126/147385405-cda67eac-8e33-4889-ad23-0139dce40767.png)
This PR solves that by getting the body's margin-right and using clip to include it in fullPage.

Of course, if you give me the issueHunt bounty, it will be great :)

2022-01-06 12:59 UTC, sindresorhus commented
> when using fullPage: true does get the whole screen, so no need to scroll around when capturing FIXED items

Does it cause lazy-loaded items further down the page to load?

2022-01-06 13:02 UTC, sindresorhus commented
> However, puppeteer does clip the body's margin-right: 

Can you open a Puppeteer issue about that?

2022-01-23 10:18 UTC, sindresorhus requested changes

2022-01-23 11:06 UTC, shemgp commented
Upon further investigation, I think this PR is not needed anymore since all it does is add the right body margin so that it's the same with the left, where as in both Chrome and Firefox, that right margin is not shown by default, so it's not a bug in Puppeteer.

Chrome:
![Screenshot from 2022-01-23 18-57-28](https://user-images.githubusercontent.com/1734126/150675313-f412db8c-b073-4f6c-afcb-8d6e2c7c3412.png)

Firefox:
![Screenshot from 2022-01-23 18-57-26](https://user-images.githubusercontent.com/1734126/150675317-3ab8b610-01fc-46a8-8435-cddf20367e0f.png)

So #1 was actually fixed already via #28. So bounty could go to the author. But could go to me to for pointing out that it's fixed :) hehe

2022-01-23 11:13 UTC, sindresorhus commented
> So #1 was actually fixed already via #28. So bounty could go to the author. But could go to me to for pointing out that it's fixed :) hehe

It was not completely fixed. See: https://github.com/sindresorhus/capture-website/pull/65

2022-01-23 11:13 UTC, closed without merging